[package]
name = "hex"
version = "0.1.0"
authors = ["tikhono <tihonovandrey11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
