[package]
name = "bytes_and_big_integers"
version = "0.1.0"
authors = ["tikhono <tihonovandrey11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uint = "0.9.0"