[package]
name = "ecb_cbc_wtf"
version = "0.1.0"
authors = ["tikhono <tikhonov.andrii.m@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.38"
hex = "0.4"
ascii = "1.0.0"
_02_fixed_xor = {path = "../../../../pals/set1/_02_fixed_xor"}
